version: "3.8"
services:
  pg11:
    image: postgres:11.4
    container_name: "pg11-1"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=secret 
      - PGDATA=/pgdata/pg11-1
    volumes:
      - /mydocker/pgdata/pg11-1:/pgdata/pg11-1
    restart: always
  
  redis:
    image: redis
    container_name: "redis-1"
    ports:
      - "6379:6379"
    volumes:
      - /mydocker/redisdata/conf:/usr/local/etc/redis
    command:  redis-server /usr/local/etc/redis/redis.conf

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-1
    volumes:
      - /mydocker/rabbitmq/etc/:/etc/rabbitmq/
      - /mydocker/rabbitmq/data/:/var/lib/rabbitmq/
      - /mydocker/rabbitmq/logs/:/var/log/rabbitmq/
    environment:
      RABBITMQ_ERLANG_COOKIE: "erlang_cookie"
      # RABBITMQ_DEFAULT_USER: guest
      # RABBITMQ_DEFAULT_PASS: password
    ports:
      - 5672:5672
      - 15672:15672

  nginx:
    image: nginx
    container_name: nginx-1
    volumes:
      - /mydocker/nginx/rp1/etc:/etc/nginx
    ports:
      - 8080:80
      - 443:443
      - 8081:8081

