version: "3.3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    container_name: elasticsearch
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data-volume:/usr/share/elasticsearch/data
    ports:
      - "9201:9200"
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.12.0
    restart: always
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5602:5601"
    depends_on:
      - elasticsearch
  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:7.12.0
    restart: always
    volumes:
      - type: bind
        source: ./logstash/tmp
        target: /tmp
      - type: bind
        source: ./logstash/data
        target: /usr/share/logstash/data
      - type: bind
        source: ./logstash/config/logstash.yaml
        target: /usr/share/logstash/config/logstash.yaml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
    read_only: true
    ports:
      - "8044:5044"
      - "9601:9600"
    depends_on:
      - elasticsearch
volumes:
  elasticsearch-data-volume:
    driver: local
