version: "3.6"

services:
  mongodb:
    image : mongo
    container_name: mongo-1
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - /home/vagrant/mongodb/mongo-1/database:/data/db
    ports:
      - 27017:27017
    restart: always

  mongo-express:
    image: mongo-express
    container_name: mongo-exp-1
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
