---
- name: Docker Installation and Validation
  hosts: localhost
  become: true

  tasks:
    - name: Install Docker prerequisites
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - software-properties-common
        state: present

    - name: Add Docker GPG key
      command: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
      args:
        creates: /usr/share/keyrings/docker-archive-keyring.gpg

    - name: Add Docker repository
      copy:
        content: |
          deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable
        dest: /etc/apt/sources.list.d/docker.list

    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Add user to Docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Ensure Docker service is enabled and running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Check if Docker service is running
      shell: systemctl is-active docker
      register: docker_status
      failed_when: docker_status.stdout.strip() != "active"

    - name: Run Docker Hello World to test installation
      command: docker run hello-world
      register: docker_hello_world
      failed_when: "'Hello from Docker!' not in docker_hello_world.stdout"

    - name: Print Docker test output
      debug:
        msg: "{{ docker_hello_world.stdout }}"
